Fix HOME variables

diff --git a/playbooks/roles/miniconda/templates/runonce_conda.sh.j2 b/playbooks/roles/miniconda/templates/runonce_conda.sh.j2
--- a/playbooks/roles/miniconda/templates/runonce_conda.sh.j2
+++ b/playbooks/roles/miniconda/templates/runonce_conda.sh.j2
@@ -21,14 +21,18 @@ echo "Running miniconda init"
 {% else -%}
 # Add miniconda/condabin (but not miniconda/bin) to the user's path so they can manually run `conda init`
 
+EXPORT_MINICONDA_PATH="export PATH=\"$MINICONDA_DEST/condabin\${PATH:+:\${PATH}}\""
+
 if [[ -n "$ZSH_VERSION" ]]; then
-  RC_FILE=~/.zshrc
+  RC_FILE="$HOME/.zshrc"
+elif [[ -n "$BASH_VERSION" ]]; then
+  RC_FILE="$HOME/.bashrc"
 else
-  # Assume bash, since runonce supports only zsh and bash anyway.
-  RC_FILE=~/.bashrc
+  echo "You are using a shell other than zsh or bash. Could not automatically setup miniconda for you. Please add the following to your shell's profile or rc file:"
+  echo "$EXPORT_MINICONDA_PATH"
+  exit 1
 fi
 
-EXPORT_MINICONDA_PATH="export PATH=\"$MINICONDA_DEST/condabin\${PATH:+:\${PATH}}\""
 eval "$EXPORT_MINICONDA_PATH" # export for the current shell
 echo "$EXPORT_MINICONDA_PATH" >> "$RC_FILE"
 {% endif -%}
diff --git a/playbooks/roles/pyenv/templates/pyenv-install.sh.j2 b/playbooks/roles/pyenv/templates/pyenv-install.sh.j2
--- a/playbooks/roles/pyenv/templates/pyenv-install.sh.j2
+++ b/playbooks/roles/pyenv/templates/pyenv-install.sh.j2
@@ -9,13 +9,6 @@ SYSTEM_PYTHON="{{ system_python_path }}"
 cd
 curl https://pyenv.run | bash
 
-if [[ -n "$ZSH_VERSION" ]]; then
-  RC_FILE=~/.zshrc
-else
-  # Assume bash, since runonce supports only zsh and bash anyway.
-  RC_FILE=~/.bashrc
-fi
-
 PYENV_INIT=$(cat <<EOF
 # added by runonce as pyenv config
 if [ -z "\$PYENV_ROOT" ]; then
@@ -26,6 +19,16 @@ eval "\$(pyenv init -)"
 eval "\$(pyenv virtualenv-init -)"
 EOF
 )
+
+if [[ -n "$ZSH_VERSION" ]]; then
+  RC_FILE="$HOME/.zshrc"
+elif [[ -n "$BASH_VERSION" ]]; then
+  RC_FILE="$HOME/.bashrc"
+else
+  echo "You are using a shell other than zsh or bash. Could not automatically setup pyenv for you. Please add the following to your shell's profile or rc file:"
+  echo "$PYENV_INIT"
+  exit 1
+fi
 
 echo "$PYENV_INIT" >> "$RC_FILE"
 eval "$PYENV_INIT" # add to current shell
