miniconda: use shell-independent profile file for conda setup (#123)
* miniconda and pyenv: refactor to make prepending to PATH more robust

diff --git a/playbooks/roles/miniconda/templates/runonce_conda.sh.j2 b/playbooks/roles/miniconda/templates/runonce_conda.sh.j2
--- a/playbooks/roles/miniconda/templates/runonce_conda.sh.j2
+++ b/playbooks/roles/miniconda/templates/runonce_conda.sh.j2
@@ -21,22 +21,18 @@ echo "Running miniconda init"
 {% else -%}
 # Add miniconda/condabin (but not miniconda/bin) to the user's path so they can manually run `conda init`
 
+EXPORT_MINICONDA_PATH="export PATH=\"$MINICONDA_DEST/condabin\${PATH:+:\${PATH}}\""
+
 if [[ -n "$ZSH_VERSION" ]]; then
-  PROFILE_FILE=~/.zprofile
-  RC_FILE=~/.zshrc
+  RC_FILE="$HOME/.zshrc"
+elif [[ -n "$BASH_VERSION" ]]; then
+  RC_FILE="$HOME/.bashrc"
 else
-  # Assume bash, since runonce supports only zsh and bash anyway.
-  PROFILE_FILE=~/.bash_profile
-  RC_FILE=~/.bashrc
+  echo "You are using a shell other than zsh or bash. Could not automatically setup miniconda for you. Please add the following to your shell's profile or rc file:"
+  echo "$EXPORT_MINICONDA_PATH"
+  exit 1
 fi
 
-if [[ -z "$PATH" ]]; then
-    # If $PATH is empty, create it
-    echo "export PATH=\"$MINICONDA_DEST/condabin\"" | tee -a "$PROFILE_FILE" "$RC_FILE"
-    export PATH="$MINICONDA_DEST/condabin"
-else
-    # Else append to $PATH
-    echo "export PATH=\"\$PATH:$MINICONDA_DEST/condabin\"" | tee -a "$PROFILE_FILE" "$RC_FILE"
-    export PATH="$PATH:$MINICONDA_DEST/condabin"
-fi
+eval "$EXPORT_MINICONDA_PATH" # export for the current shell
+echo "$EXPORT_MINICONDA_PATH" >> "$RC_FILE"
 {% endif -%}
diff --git a/playbooks/roles/pyenv/templates/pyenv-install.sh.j2 b/playbooks/roles/pyenv/templates/pyenv-install.sh.j2
--- a/playbooks/roles/pyenv/templates/pyenv-install.sh.j2
+++ b/playbooks/roles/pyenv/templates/pyenv-install.sh.j2
@@ -9,20 +9,29 @@ SYSTEM_PYTHON="{{ system_python_path }}"
 cd
 curl https://pyenv.run | bash
 
-cat >>~/.bashrc <<'INPUTEND'
+PYENV_INIT=$(cat <<EOF
 # added by runonce as pyenv config
-if [ -z "$PYENV_ROOT" ]; then
-export PYENV_ROOT="$HOME/.pyenv"
-export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
+if [ -z "\$PYENV_ROOT" ]; then
+export PYENV_ROOT="\$HOME/.pyenv"
+export PATH="\$PYENV_ROOT/shims:\$PYENV_ROOT/bin\${PATH:+:\${PATH}}"
 fi
-eval "$(pyenv init -)"
-eval "$(pyenv virtualenv-init -)"
-INPUTEND
+eval "\$(pyenv init -)"
+eval "\$(pyenv virtualenv-init -)"
+EOF
+)
 
-# also add pyenv to current login shell 
-# so that pyenv commands can be used in other runonce actions
-export PYENV_ROOT="$HOME/.pyenv"
-export PATH="$PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH"
+if [[ -n "$ZSH_VERSION" ]]; then
+  RC_FILE="$HOME/.zshrc"
+elif [[ -n "$BASH_VERSION" ]]; then
+  RC_FILE="$HOME/.bashrc"
+else
+  echo "You are using a shell other than zsh or bash. Could not automatically setup pyenv for you. Please add the following to your shell's profile or rc file:"
+  echo "$PYENV_INIT"
+  exit 1
+fi
+
+echo "$PYENV_INIT" >> "$RC_FILE"
+eval "$PYENV_INIT" # add to current shell
 
 if [[ -n "$DEFAULT_PYTHON_VERSION" ]]; then
     if [[ "$DEFAULT_PYTHON_VERSION" != system* ]]; then
